config/routes.rb
ShoppingCart::Application.routes.draw do
  
  post 'login' => 'sessions#new', :as => 'login'
  post 'logout' => 'sessions#destroy', :as => 'logout'
  post 'signup' => 'users#new', :as=>'signup'
  root :to => 'shopping_lists#index'
  put 'users/add/:id' => 'users#add_item'
  post 'users/make_list_active' => 'users#make_list_active'
  get 'sales' => 'orders#sales_index'
  post 'items/remove' => 'shopping_lists#remove_item'

  resources :orders
  resources :shops
  resources :items #do 
  resources :users
  resources :shopping_lists
  resources :sessions

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  attr_accessible :user_id, :name
  belongs_to :user
  has_many :items
  validate :user_exists?


  # Orders are tied to both the seller and buyer
  has_many :sales, :class_name => 'Order'

  def user_exists?()
    unless User.find_by_id(user_id)
        errors[:base] << "User does not exist"
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  include ApplicationHelper

  def index
    @shops = Shop.all

    respond_to do |format|
      format.html
      format.json { render json: @shops }
    end
  end


  def show
    @shop = Shop.find(params[:id])
    @items = @shop.items.where("ordered" => false)

    respond_to do |format|
      format.html
      format.json { render json: @shop }
    end
  end


  def new
    @shop = Shop.new

    respond_to do |format|
      format.html
      format.json { render json: @shop }
    end
  end

 
  def edit
    @shop = Shop.find(params[:id])
    unless can_modify_shop?(@cur_user, @shop) 
      redirect_to shopping_lists_url, :notice => "You do not have permission to do that"
    end
  end


  def create
    params[:shop][:user_id] = @cur_user.id
    @shop = Shop.new(params[:shop])
    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @shop = Shop.find(params[:id])
    unless can_modify_shop?(@cur_user, @shop) 
      redirect_to shopping_lists_url, :notice => "You do not have permission to do that"
    end
    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @shop = Shop.find(params[:id])
    unless can_modify_shop?(@cur_user, @shop) 
      redirect_to shopping_lists_url, :notice => "You do not have permission to do that"
    end
    @shop.destroy
    flash.alert = "Shop destroyed"
    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <% @shop.errors.full_messages.each do |msg| %>
        <div class="error_message"><%= msg %></div>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Managing <%=@shop.name%></h1>

<%= render 'form' %>

<div class="add-item">
<%= link_to 'Add Item', new_item_path(:shop_id => @shop.id) %>
<%= link_to("Delete", @shop, :method => :delete, :class => 'action') %>
</div>
<br>
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<%= render :partial => "layouts/nav", :locals => {:active => "shops"}%>
<br><br>
<% @shops.each do |shop| %>
	<div class="span3"><%= link_to shop.name, shop %></div>
<% end %>

<br >
<hr>

<% unless @cur_user.temp %>
	<%= link_to 'New Shop', new_shop_path %>
<% end %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<% if @shop.user_id != @cur_user.id %>
	<span class="owner">
		<%= link_to "See Owner", {:controller=> "users", :action=> "show", :id => @shop.user_id} %>
	</span>
<% else %>
	<span class="manage">
		<%= link_to 'Manage Shop', edit_shop_path(@shop) %>
	</span>
<% end %>

<% @items.each do |item| %>
	<div class="item">
		<span class="name"><%=item.name %></span>
		<span class="price">$<%=item.price.round(2) %></price>
		<span class="action">
			<% if @shop.user_id != @cur_user.id %>
				<%= link_to "Add to list", {:controller=> "users", :action=>"add_item", :id=>item.id },:method=>"put" %>
			<% else %>
				<%= link_to "Edit", {:controller=> "items", :action=>"edit", :id=>item.id} %>
				<%= link_to "Remove", {:controller=> "items", :action=>"destroy"}, :method => :delete %> 
			<% end %>
		</span>
	</div>
<% end %>

<hr>
<span class="back">
<%= link_to 'Back', shops_path %>
</span>