config/routes.rb
ShoppingCart::Application.routes.draw do
  
  post 'login' => 'sessions#new', :as => 'login'
  post 'logout' => 'sessions#destroy', :as => 'logout'
  post 'signup' => 'users#new', :as=>'signup'
  root :to => 'shopping_lists#index'
  put 'users/add/:id' => 'users#add_item'
  post 'users/make_list_active' => 'users#make_list_active'
  get 'sales' => 'orders#sales_index'
  post 'items/remove' => 'shopping_lists#remove_item'

  resources :orders
  resources :shops
  resources :items #do 
  resources :users
  resources :shopping_lists
  resources :sessions

end

app/models/user.rb
class User < ActiveRecord::Base
  # Keeping tracking of active_list_id so that I don't have to keep track
  # of whether a shopping list is "active" and so that I don't have to query
  # all of a user's shopping_lists to find the one that has "active=true"

  VALID_EMAIL_REGEX = /^.+@.+\..+$/i 
  attr_accessible :active_list_id, :password, :password_confirmation, :email, :temp, :auth_token
  attr_accessor :password, :password_confirmation

  before_create { generate_token(:auth_token) }
  # Initialize a cart

  before_validation :downcase_email

  validates_presence_of :email, :password, :password_confirmation, 
                          :on => :create, 
                          :unless => "temp"
   
  validates :password, :length => (6..32), 
                       :confirmation => true, 
                       :if => :setting_password?

    #something@something.something
  validates :email, :uniqueness => true, 
              :format => {:with => VALID_EMAIL_REGEX },
              :unless => "temp"

  # Create the user's shopping cart
  after_create { 
    make_list(:name => email ? email+"'s shopping list" : "Anonymous' shopping list") 
  }

  has_many :shopping_lists
  has_many :shops
  has_many :transactions, :class_name => 'Order'
  

  HUMANIZED_ATTRIBUTES = {
    :password_digest => "Password"
  }

# Setter method for password. Sets up the passowrd_salt and password_digest for future verification.
 def password=(password_str)
    @password = password_str
    write_attribute(:password_salt,BCrypt::Engine.generate_salt)
    write_attribute(:password_digest,BCrypt::Engine.hash_secret(password_str, password_salt))
  end

  # Used to tell if we need to validate the password
  def setting_password?
    self.password || self.password_confirmation
  end
 
  # Checks if the user provided the correct password
  def authenticate(password)
    password.present? && password_digest.present? && password_digest == BCrypt::Engine.hash_secret(password, password_salt)
  end

  # Creates a "default" list
  def factory_list
    make_list(:name=>"Anon's List")
  end

  # Makes a cart and sets that cart to be the currently active cart
  def make_list(params)
  	active_list = self.shopping_lists.new(params)
    active_list.temp = temp
    puts "saving list"
    puts save
  	return set_active_list(active_list)
  end

  # Finds all order transactions
  def get_orders
    return Order.where("buyer_id" => id)
  end

  # Finds all sales transactions
  def get_sales
    return Order.where("seller_id" => id)
  end

  # Transfers list from temp_user to the current user.
  # Called at login.
  def transfer_list_over(temp_user)
    temp_list = ShoppingList.find_by_id(temp_user.active_list_id)
    if !temp_list.items.empty?
      temp_list.user_id = self.id
      temp_list.temp = false
      temp_list.save
      self.active_list_id = temp_list.id
    else
      temp_list.destroy
    end
    return save
  end

  # Returns the active list
  def get_active_list()
    return ShoppingList.find_by_id(active_list_id)
  end

  # Adds an item to the currently active list
  def add_to_list(item)
    unless ShoppingList.find_by_id(active_list_id)
      make_list(:name => email+"'s shopping list")
    end
    puts active_list_id
    return get_active_list().items << item
  end

  # Sets the currently active_list_id
  def set_active_list(list)
    self.active_list_id = list.id
    save
    return
  end

  # Changes the password
  def change_password_digest(digest)
  	return update_attribute(:password_digest, digest)
  end

  # Authorization token for validating user
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column]) 
  end

  # Overrides humanized attribute names
  def self.human_attribute_name(attr, options={})
    HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end

  # Downcase email because emails are usually not case sensitive
  def downcase_email
    self.email = self.email.downcase if self.email.present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  # Display relevant information about a user.
  def show
    @user = User.find_by_id(params[:id])
    if @user.id == @cur_user.id
      @shopping_lists = @user.shopping_lists
    else
      @shopping_lists = @user.shopping_lists.where(:public => true)
    end
    respond_to do |format|
      format.html
      format.json { render json: @user }
    end
  end

  # Adds an item to the current user's active list.
  def add_item 
    item = Item.find_by_id(params[:id])
    unless item
      flash.alert = "No item with that ID exists"
      redirect_to session.delete(:return_to)
      return
    end
    unless @cur_user.add_to_list(item)
      flash.alert = "No item with that ID exists"
      redirect_to session.delete(:return_to) 
      return
    end
    redirect_to session.delete(:return_to), :notice=> "The item has been successfully added!"
  end

  # Sets a user's active list
  def make_list_active
    list = ShoppingList.find_by_id(params[:list_id])
    if list
      if can_modify_list?(@cur_user, list)
        @cur_user.set_active_list(list)
        redirect_to root_url, :notice=>"list now active!"
      else
        flash.alert = "That list does not belong to you"
        redirect_to session.delete(:return_to)
      end
    else
      flash.alert = "That list does not exist"
      redirect_to session.delete(:return_to)
    end
  end

  # Shows the signup form for creating a new user
  def new
    @user = User.new
  end

  # Handles the creation of a new user.
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <% @user.errors.full_messages.each do |msg| %>
        <div class="error_message"><%= msg %></div>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br />
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.text_field :cart_id %>
  </div>
  <%= f.hidden_field :temp, :value => false %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/lists.html.erb
<div id="lists">
	<% @cur_user.shopping_lists.each do |list| %>
		<span class="list-name">list.name</span>
		<% button_to "Edit list" edit_list_url %>
		<% button_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %>
		<br />
	<% end %>
</div>

app/views/users/new.html.erb
<h1> Sign Up</h1>

<p id="notice"><%= notice %></p>

<%= form_for @user do |f| %>
		<% if @user.errors.any? %>
			<div class="error_messages">
				<h2> Form is invalid</h2>
				<ul>
						<% for message in @user.errors.full_messages %>
							<li><%= message %></li>
						<% end %>
				</ul>
			</div>
		<% end %>
	<div class="field">
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %>
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</div>
	<div class ="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.temp ? 'Anon' : @user.email %>
</p>

<div class="row-fluid">
	<div class="span4 offset2 lists">
		<h1 style="text-align:center">Lists</h1>
		<% @user.shopping_lists.each do |list| %>
			<div class="list-item">
				<span class="name">
					<%= link_to list.name, shopping_list_url(:id=>list.id) %>
				</span>
			</div>
		<% end %>
	</div>
	<div class="span4 shops">
		<h1 style="text-align:center">Shops</h1>
		<% @user.shops.each do |shop| %>
			<div class="shop">
				<%= link_to shop.name, shop %>
			</div>
		<% end %>
	</div>
</div>
<hr>

<%= link_to 'Back', :back %>