config/routes.rb
ShoppingCart::Application.routes.draw do
  
  post 'login' => 'sessions#new', :as => 'login'
  post 'logout' => 'sessions#destroy', :as => 'logout'
  post 'signup' => 'users#new', :as=>'signup'
  root :to => 'shopping_lists#index'
  put 'users/add/:id' => 'users#add_item'
  post 'users/make_list_active' => 'users#make_list_active'
  get 'sales' => 'orders#sales_index'
  post 'items/remove' => 'shopping_lists#remove_item'

  resources :orders
  resources :shops
  resources :items #do 
  resources :users
  resources :shopping_lists
  resources :sessions

end

app/models/shopping_list.rb
class ShoppingList < ActiveRecord::Base
  attr_accessible :name, :user_id, :temp, :public
  has_and_belongs_to_many :items
  belongs_to :user

  validates_presence_of :name, :user_id

  validates :name, :length => { :minimum => 3 }

  def get_total_price
  	return self.items.to_a.sum(&:price)
  end

  def get_item_count
  	return self.items.length
  end

  # Creates a deep copy of the shopping list items as an array
  # This is used for creating an order with this list
  def clone_list_to_array
    clone = Array.new
    self.items.each do |item| 
      result.push(item.get_clone())
    end
    return clone
  end
  
  # To remove the item it counts how many of that items 
  # existed before. It is done this way because of a limitation
  # on delete. In the future this should be changed by moving shopping
  # list items to a subclass of item that has a count indicating how 
  # many of said item are in the cart.
  def remove_item(user, item)
    before = get_item_count
    self.items.delete(item)
    after = get_item_count
    (before-after-1).times do
      user.add_to_list(item)
    end
  end

end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  include ApplicationHelper

  # Displays all shopping lists that do not belong to temporary users
  def index
    @shopping_lists = ShoppingList.where("temp" => false, "public"=> true)
    respond_to do |format|
      format.html
      format.json { render json: @shopping_lists }
    end
  end

  # Displays a specific shopping list.
  def show
    @shopping_list = ShoppingList.find(params[:id])
    unless @shopping_list || (@shopping_list.public && can_modify_list?(@cur_user, @shopping_list))
      redirect_to root_url, :notice=> "Could not find that list"
      return
    end
    @items = @shopping_list.items.where("ordered" => false)
    respond_to do |format|
      format.html 
      format.json { render json: @shopping_list }
    end
  end

  # Makes a new list
  def new
    if @cur_user.temp
      flash.alert = "Must be logged in to make new list"
      redirect_to shopping_lists_url
      return
    else
      @shopping_list = ShoppingList.new

      respond_to do |format|
        format.html 
        format.json { render json: @shopping_list }
      end
    end
  end

  def edit
    if @cur_user.temp
      flash.alert = "Must be logged in to do that"
      redirect_to session.delete(:return_to)
      return
    end
    @shopping_list = ShoppingList.find_by_id(params[:id])
    unless can_modify_list?(@cur_user, @shopping_list)
      redirect_to session.delete(:return_to), :notice=> "You do not have permission to do that"
    end
  end

  def create
    if @cur_user.temp
      flash.alert = "Must be logged in to make new list"
      redirect_to shopping_lists_url
      return
    end
    if @cur_user.make_list(params[:shopping_list])
      puts @cur_user.active_list_id 
      @shopping_list = ShoppingList.find_by_id(@cur_user.active_list_id)
      redirect_to root_url, :notice=> 'Shopping list was successfully created.' 
    else
      redirect_to root_url, :notice=> "Creation failed"
    end
  end

  def update
    @shopping_list = ShoppingList.find(params[:id])
    if @cur_user.temp
      flash.alert = "Must be logged in to do that"
      redirect_to session.delete(:return_to)
      return
    end
    unless can_modify_list?(@cur_user, @shopping_list)
      redirect_to session.delete(:return_to), :notice=> "You do not have permission to do that"
    end
    respond_to do |format|
      if @shopping_list.update_attributes(params[:shopping_list])
        format.html { redirect_to @shopping_list, notice: 'Shopping list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shopping_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_item
    @shopping_list = ShoppingList.find_by_id(params[:list_id])
    @item = Item.find_by_id(params[:item_id])
    unless @shopping_list || @item || can_modify_list?(@cur_user, @shopping_list) \
            ||   list_has_item?(shopping_list, @item)

      redirect_to shopping_lists_url, :notice => "You can't do that"
    end
    unless @shopping_list.remove_item(@cur_user, @item)
      redirect_to shopping_lists_url, :notice => "An unknown error has occurred"
    end
    redirect_to session.delete(:return_to), :notice => "The item has been removed!"
  end

  def destroy
    @shopping_list = ShoppingList.find(params[:id])
    unless can_modify_list?(@cur_user, @shopping_list) 
      redirect_to shopping_lists_url, :notice => "You do not have permission to do that"
    end
    @shopping_list.destroy
    flash.alert = "Shopping list destroyed"
    respond_to do |format|
      format.html { redirect_to shopping_lists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/shopping_lists/_form.html.erb
<%= form_for(@shopping_list) do |f| %>
  <% if @shopping_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopping_list.errors.count, "error") %> prohibited this shopping_list from being saved:</h2>

      <% @shopping_list.errors.full_messages.each do |msg| %>
        <div class="error_message"><%= msg %></div>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="checkbox">
    <%= f.check_box :public %>
    <%= f.label :public %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopping_lists/edit.html.erb
<h1>Editing shopping_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopping_list %> |
<%= link_to 'Back', :back %>

app/views/shopping_lists/index.html.erb
<%= render :partial => "layouts/nav", :locals => {:active => "lists"} %>
<br><br>
<% @shopping_lists.each do |shopping_list| %>
  <%= link_to shopping_list.name, shopping_list %><br />
<% end %>

<br >
<hr>

<% unless @cur_user.temp %>
	<%= link_to 'New Shopping list', new_shopping_list_path %>
<% end %>

app/views/shopping_lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/shopping_lists/show.html.erb
<p id="notice"><%= notice %></p>


<h2> <%= @shopping_list.name %></h2>
<br>
<% if can_modify_list?(@cur_user, @shopping_list) && !is_temp_user?(@cur_user) %>
	<% if is_active_list?(@cur_user, @shopping_list) %>
		<span class="active">This is your currently active list</span>
	<% else %>
		<span class="inactive">
			<%= link_to "Make this your active list", {:controller=>'users', :action=>'make_list_active', :list_id=> @shopping_list.id}, :method=>'post' %>
		</span>
	<% end %>
	<span class="edit" style="margin-left:40px">
		<%= link_to 'Edit', edit_shopping_list_path(@shopping_list) %>
	</span>
	<span class="delete" style="margin-left:40px">
			<%= link_to("Delete", @shopping_list, :method => :delete, :class => 'action') %>
		</span> 
		<br><br>
<% end %>

<% unless @shopping_list.items.empty? %>
	<h3>Items:</h3>
		<div class="items">
			<% @items.each do |item| %>
				<div class="item">
					<span class="name" style="margin-right:20px"><%= item.name %></span>
					<span class="price" style="margin-right:20px">$<%= item.price.round(2) %></span>
					<span class="store" style="margin-left:20px">
						<%= link_to "Visit Store", shop_url(:id => item.shop_id) %>
					</span>
					<span class="remove" style="margin-left:20px">
						<%= link_to "Remove Item", {:controller=>'shopping_lists', :action=>'remove_item', :item_id=>item.id, :list_id=>@shopping_list.id}, :method=>"post" %>
					</span>
				</div>
			<% end %>
		</div>
		<% if can_modify_list?(@cur_user, @shopping_list) && !@items.empty? %>
			<div class="total" >Total: $<%= @items.sum(:price).round(2) %></div>
			<br>
			<div class="bottom-nav">
				<% unless @cur_user.temp %>
				<span class="edit"><%= link_to 'Edit', edit_shopping_list_path(@shopping_list) %></span>
				<% end %>
				<span class="order-this"><%= link_to "Order this list!", {:controller=>"orders", :action=>"create",
										:list_id => @shopping_list.id}, :method => "post" %>
				</span>
			</div>

		<% end %>
<% else %>
	<p style="font-style:italic">There are no items to see :(</p>
<% end %>
<hr>
<%= link_to 'All Lists', shopping_lists_url %>